// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAq4oTxId9Q-APfiRRO9Ckn4JGvMKLITk',
    appId: '1:230312261280:web:99f474a3df48b2a0a57bc5',
    messagingSenderId: '230312261280',
    projectId: 'novice-butler',
    authDomain: 'novice-butler.firebaseapp.com',
    storageBucket: 'novice-butler.appspot.com',
    measurementId: 'G-M7BCBD4P7Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAWG7H-ZaPYAJw6NTwD_mvqOwvWrs9Tyc',
    appId: '1:230312261280:android:fb97ce273a09c1f6a57bc5',
    messagingSenderId: '230312261280',
    projectId: 'novice-butler',
    storageBucket: 'novice-butler.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlkM-oqphioL4NXqLpt3VxCHadHMfhO5M',
    appId: '1:230312261280:ios:ec40ecaa5c52347da57bc5',
    messagingSenderId: '230312261280',
    projectId: 'novice-butler',
    storageBucket: 'novice-butler.appspot.com',
    iosBundleId: 'com.example.noviceButler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlkM-oqphioL4NXqLpt3VxCHadHMfhO5M',
    appId: '1:230312261280:ios:ec40ecaa5c52347da57bc5',
    messagingSenderId: '230312261280',
    projectId: 'novice-butler',
    storageBucket: 'novice-butler.appspot.com',
    iosBundleId: 'com.example.noviceButler',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAq4oTxId9Q-APfiRRO9Ckn4JGvMKLITk',
    appId: '1:230312261280:web:3489eba6a1324c4fa57bc5',
    messagingSenderId: '230312261280',
    projectId: 'novice-butler',
    authDomain: 'novice-butler.firebaseapp.com',
    storageBucket: 'novice-butler.appspot.com',
    measurementId: 'G-NWZ5E6C7D8',
  );
}
